name: pr_audit
on:
  pull_request:
    branches: [main]
jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Read release.json
        uses: notiz-dev/github-action-json-property@release
        id: package_info
        with:
          path: release.json
          prop_path: go_version
      - run: echo "version is ${{ steps.package_info.outputs.prop }}"
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.package_info.outputs.prop }}
      - name: Install Mockery
        run: go install github.com/vektra/mockery/v2@v2.20.0
      - name: Run go generate
        run: go generate ./...
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -v ./...
      - name: Run go vet
        run: go vet ./...
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run staticcheck
        run: staticcheck ./...
      - name: Install golint
        run: go install golang.org/x/lint/golint@latest
      - name: Run golint
        run: golint -set_exit_status ./...
      - name: Run tests
        run: go test -race -vet=off ./...
