name: pr_test
on:
  pull_request:
    branches: [main]
jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Read release.json
        uses: notiz-dev/github-action-json-property@release
        id: package_info
        with:
          path: release.json
          prop_path: go_version
      - run: echo "version is ${{ steps.package_info.outputs.prop }}"
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.package_info.outputs.prop }}
      - name: Install Mockery
        run: go install github.com/vektra/mockery/v2@v2.20.0
      - name: Run go generate
        run: go generate ./...
      - name: Run go test
        run: go test ./...
